<?php

declare(strict_types=1);

namespace Modules\PortalAdministration\Database\Seeders\Portal;

class PenghargaanSeeder extends PortalPageSeeder
{
    public function run(): void
    {
        $this->seedBlockPage('penghargaan', [
            ['type' => 'hero', 'id' => 'ph_hero', 'data' => [
                'title_ms' => 'PENGHARGAAN',
                'title_en' => 'ACKNOWLEDGEMENT',
            ]],
            ['type' => 'text', 'id' => 'ph_penghargaan', 'data' => [
                'icon'       => '💬',
                'heading_ms' => 'PENGHARGAAN',
                'heading_en' => 'ACKNOWLEDGEMENT',
                'text_ms'    => "Salam Sejahtera,\n\nSegala puji-pujian bagi Tuhan sekalian alam. Saya ingin mengucapkan setinggi-tinggi terima kasih kepada pihak Opensoft Technologies kerana memberi saya peluang keemasan untuk menjalani latihan industri di sini. Pengalaman ini amat bermakna kerana saya berpeluang mendalami teknologi moden seperti kerangka kerja (framework) Laravel dalam pembangunan sistem sebenar.\n\nTidak dilupakan, penghargaan buat ibu bapa dan keluarga saya yang sentiasa memberi dorongan, sokongan padu, serta semangat untuk saya menghadapi setiap cabaran sepanjang tempoh latihan industri dan pengajian saya di Politeknik Sultan Idris Shah.\n\nTerima kasih yang tidak terhingga kepada penyelia saya serta seluruh warga kerja Opensoft Technologies yang tidak jemu memberi tunjuk ajar dalam aspek teknikal pembangunan perisian. Mereka memberikan layanan yang sangat baik dan sentiasa bekerjasama terutamanya ketika saya mendalami konsep MVC (Model-View-Controller) dan pengurusan pangkalan data. Kepercayaan yang diberikan untuk saya mengendalikan tugasan mencabar telah membina keyakinan diri saya untuk menjadi lebih berdikari dan profesional. Akhir kata, terima kasih juga saya ucapkan kepada para pensyarah dan rakan-rakan yang sentiasa menyokong perjalanan latihan industri saya ini.",
                'text_en'    => "Greetings,\n\nAll praise be to God. I would like to express my deepest gratitude to Opensoft Technologies for giving me the golden opportunity to undergo industrial training here. This experience is truly meaningful as I had the chance to explore modern technologies such as the Laravel framework in real-world system development.\n\nSpecial appreciation goes to my parents and family who have always provided encouragement, full support, and motivation for me to face every challenge throughout my industrial training and studies at Politeknik Sultan Idris Shah.\n\nHeartfelt thanks to my supervisor and all staff at Opensoft Technologies who tirelessly guided me in the technical aspects of software development. They provided excellent service and always cooperated, especially when I was learning MVC (Model-View-Controller) concepts and database management. The trust given to me to handle challenging tasks has built my confidence to become more independent and professional. Last but not least, I would also like to thank my lecturers and friends who have always supported my industrial training journey.",
            ]],
            ['type' => 'text', 'id' => 'ph_ringkasan', 'data' => [
                'heading_ms' => 'RINGKASAN EKSEKUTIF',
                'heading_en' => 'EXECUTIVE SUMMARY',
                'text_ms'    => "Ringkasan aktiviti latihan industri ialah satu ringkasan tugas yang telah diberikan kepada para pelajar oleh penyelia atau pengurus di sesuatu organisasi. Tujuannya adalah untuk merekodkan pengalaman dan kemahiran teknikal yang diperoleh sepanjang tempoh latihan. Setiap aktiviti atau tugas yang dijalankan dicatat dengan teliti dalam buku laporan harian. Oleh itu, bahagian ini menjelaskan secara ringkas aktiviti dan tugasan saya yang telah dijalankan di Opensoft Technologies dalam jangka masa satu semester iaitu selama dua puluh minggu. Segala aktiviti yang dilakukan diterangkan dari minggu ke minggu bagi merumuskan kerja-kerja yang telah disiapkan di samping memudahkan proses penyemakan aktiviti mingguan yang merangkumi hari kerja biasa serta cuti umum yang ditetapkan.\n\nSkop tugas yang diberikan kepada saya tertumpu kepada pembangunan sistem menggunakan kerangka kerja (framework) Laravel, pengurusan pangkalan data SQL, serta penyelenggaraan sistem sedia ada. Secara ringkasnya, tugasan yang telah saya jalankan merangkumi pembangunan modul pentadbir (admin), melakukan kemas kini keselamatan bagi menangani kerentanan sistem (vulnerability fixes), serta menguruskan kawalan versi kod menggunakan Git. Selain itu, saya juga terlibat dalam penyediaan dokumentasi teknikal seperti manual pengguna, melakukan pengujian sistem (testing), serta memastikan integrasi pangkalan data berjalan lancar. Pengalaman mengendalikan perisian seperti Laragon, SQLyog, dan VS Code sepanjang tugasan ini telah memantapkan lagi kemahiran teknikal saya dalam persekitaran pembangunan perisian yang sebenar.\n\nSebagai kesimpulan, latihan industri di Opensoft Technologies ini adalah satu platform yang sangat penting kerana ia membolehkan kemahiran pengaturcaraan yang dipelajari di dewan kuliah diaplikasikan secara praktikal. Ia bukan sahaja mengasah kemahiran teknikal dalam bidang teknologi maklumat, malah menjadi medium untuk membina keyakinan diri dan profesionalisme bagi menghadapi alam pekerjaan sebenar yang bakal ditempuhi pada masa akan datang.",
                'text_en'    => "The industrial training activity summary is a summary of tasks assigned to students by supervisors or managers at an organisation. Its purpose is to record the experiences and technical skills acquired throughout the training period. Every activity or task carried out is carefully recorded in the daily report book. Therefore, this section briefly explains the activities and tasks I carried out at Opensoft Technologies over a period of one semester, which is twenty weeks. All activities are described on a weekly basis to summarise the work completed while facilitating the review process of weekly activities covering regular working days and public holidays.\n\nThe scope of tasks assigned to me focused on system development using the Laravel framework, SQL database management, and maintenance of existing systems. In summary, the tasks I carried out included developing admin modules, performing security updates to address system vulnerabilities (vulnerability fixes), and managing code version control using Git. In addition, I was also involved in preparing technical documentation such as user manuals, conducting system testing, and ensuring smooth database integration. The experience of using software such as Laragon, SQLyog, and VS Code throughout these tasks has further strengthened my technical skills in a real software development environment.\n\nIn conclusion, the industrial training at Opensoft Technologies is a very important platform as it enables programming skills learned in the lecture hall to be applied practically. It not only sharpens technical skills in information technology but also serves as a medium to build self-confidence and professionalism in preparation for the real working world ahead.",
            ]],
        ]);
    }
}
