<?php

declare(strict_types=1);

namespace Modules\PortalAdministration\Database\Seeders\Portal;

class RingkasanAktivitiSeeder extends PortalPageSeeder
{
    public function run(): void
    {
        $weeks = [
            ['title_ms' => 'MINGGU 1', 'title_en' => 'WEEK 1', 'start_date' => '2026-01-12', 'end_date' => '2026-01-16', 'days' => [
                ['day_ms' => 'Isnin', 'day_en' => 'Monday', 'activities_ms' => ['Lapor Diri Secara Atas Talian.', 'Menghubungi Jabatan Sumber Manusia melalui platform digital untuk pengesahan kehadiran.', 'Menghantar borang-borang keperluan syarikat dan politeknik.'], 'activities_en' => ['Online check-in.', 'Contacted Human Resources Department through digital platform for attendance verification.', 'Submitted required company and polytechnic forms.']],
                ['day_ms' => 'Selasa', 'day_en' => 'Tuesday', 'activities_ms' => ['Orientasi Kendiri dan Pemahaman Latar Belakang Syarikat.', 'Meneliti senarai perkhidmatan atau produk yang ditawarkan oleh syarikat.', 'Mengenalpasti fungsi setiap jabatan.', 'Menyediakan persiapan dokumen fizikal untuk sesi lapor diri pada pejabat hari berikutnya.'], 'activities_en' => ['Self-orientation and understanding company background.', 'Reviewed the list of services or products offered by the company.', 'Identified the function of each department.', 'Prepared physical documents for office check-in the following day.']],
                ['day_ms' => 'Rabu', 'day_en' => 'Wednesday', 'activities_ms' => ['Lapor Diri Fizikal dan Sesi Orientasi Jabatan.', 'Melapor diri kepada penyelia dan bahagian Sumber Manusia (HR).', 'Sesi suai kenal bersama ahli pasukan dan melihat kawasan sekitar pejabat.', 'Menerima taklimat mengenai peraturan syarikat dan tugasan yang bakal diberikan.', 'Mengemas kini dan menyediakan ruang kerja/meja kerja.'], 'activities_en' => ['Physical check-in and department orientation session.', 'Reported to supervisor and Human Resources (HR) department.', 'Ice-breaking session with team members and toured office surroundings.', 'Received briefing on company regulations and upcoming tasks.', 'Set up and prepared workspace/desk.']],
                ['day_ms' => 'Khamis', 'day_en' => 'Thursday', 'activities_ms' => ['Penyediaan Dokumentasi Manual Pengguna bagi Sistem mySafe (Bahagian Fungsi Butang).', 'Meneliti dan mengenalpasti fungsi setiap butang yang terdapat dalam Sistem mySafe.', 'Menyusun maklumat fungsi butang ke dalam bentuk jadual bagi memudahkan pemahaman pengguna.', 'Mendokumentasikan fungsi butang utama seperti butang \'Menu\' untuk navigasi sistem.', 'Memastikan ikon yang digunakan dalam dokumentasi sepadan dengan ikon sebenar dalam sistem.'], 'activities_en' => ['Prepared User Manual Documentation for mySafe System (Button Functions Section).', 'Studied and identified the function of each button in the mySafe System.', 'Organised button function information into table format for easier user understanding.', 'Documented main button functions such as the \'Menu\' button for system navigation.', 'Ensured icons used in documentation matched actual icons in the system.']],
                ['day_ms' => 'Jumaat', 'day_en' => 'Friday', 'activities_ms' => ['Penyediaan Dokumentasi Modul Pentadbiran bagi Sistem mySafe.', 'Meneliti fungsi Modul Pentadbiran merangkumi Pengurusan Data Induk dan Tetapan Sistem.', 'Melengkapkan manual bagi sub-modul utama bermula dari Tempat, Syarikat, Pengguna sampai ke CMS.'], 'activities_en' => ['Prepared Administration Module Documentation for mySafe System.', 'Studied the Administration Module functions covering Master Data Management and System Settings.', 'Completed manual for main sub-modules from Location, Company, User to CMS.']],
            ], 'reflection_ms' => 'Aktiviti minggu ini melibatkan proses lapor diri secara atas talian dan fizikal serta sesi orientasi sistem mySafe. Tugasan utama adalah menyediakan Manual Pengguna yang merangkumi dokumentasi fungsi butang dan Modul Pentadbiran. Saya berjaya memahami aliran kerja teknikal sistem mySafe serta mempelajari cara penulisan dokumentasi yang ringkas dan mudah difahami. Pengalaman menguruskan sub-modul secara sistematik telah meningkatkan kemahiran teknikal saya dalam memahami struktur data sistem maklumat dan cara berkomunikasi secara profesional di pejabat. Latihan ini meningkatkan keyakinan saya dalam mengendalikan dokumentasi sistem dan memupuk sifat teliti bagi mengelakkan ralat maklumat. Secara keseluruhan, saya mendapat gambaran mengenai tugas sokongan IT dan kepentingan pengurusan data yang teratur dalam sesebuah organisasi.', 'reflection_en' => 'This week\'s activities involved the process of online and physical check-in as well as mySafe system orientation sessions. The main task was to prepare a User Manual covering button function documentation and the Administration Module. I managed to understand the technical workflow of the mySafe system and learned how to write concise and easy-to-understand documentation. The experience of managing sub-modules systematically has enhanced my technical skills in understanding information system data structures and communicating professionally in the office. This training increased my confidence in handling system documentation and cultivated meticulousness to avoid information errors. Overall, I gained an overview of IT support tasks and the importance of organised data management in an organisation.'],
            ['title_ms' => 'MINGGU 2', 'title_en' => 'WEEK 2', 'start_date' => '2026-01-19', 'end_date' => '2026-01-23', 'days' => [
                ['day_ms' => 'Isnin', 'day_en' => 'Monday', 'activities_ms' => ['Menyambung penyediaan Manual Pengguna bagi Sistem mySafe.', 'Fokus kepada sub-modul Tetapan Sistem sehingga bahagian Meja Bantuan (Helpdesk).', 'Melengkapkan separuh daripada panduan konfigurasi untuk rujukan pengguna.'], 'activities_en' => ['Continued preparing User Manual for mySafe System.', 'Focused on System Settings sub-module up to Helpdesk section.', 'Completed half of the configuration guide for user reference.']],
                ['day_ms' => 'Selasa', 'day_en' => 'Tuesday', 'activities_ms' => ['Melengkapkan baki dokumentasi Manual Pengguna bagi sub-modul Meja Bantuan.', 'Menyusun keseluruhan manual mengikut turutan kedudukan butang dalam sistem.', 'Melakukan semakan akhir bagi memastikan setiap fungsi didokumentasikan dengan tepat.'], 'activities_en' => ['Completed remaining User Manual documentation for Helpdesk sub-module.', 'Organised entire manual following button placement order in the system.', 'Performed final review to ensure every function was documented accurately.']],
                ['day_ms' => 'Rabu', 'day_en' => 'Wednesday', 'activities_ms' => ['Cuti Kecemasan (Emergency Leave).'], 'activities_en' => ['Emergency Leave.']],
                ['day_ms' => 'Khamis', 'day_en' => 'Thursday', 'activities_ms' => ['Cuti Kecemasan (Emergency Leave).'], 'activities_en' => ['Emergency Leave.']],
                ['day_ms' => 'Jumaat', 'day_en' => 'Friday', 'activities_ms' => ['Cuti Kecemasan (Emergency Leave).'], 'activities_en' => ['Emergency Leave.']],
            ], 'reflection_ms' => 'Aktiviti minggu kedua memfokuskan kepada penyambungan baki Manual Pengguna bagi modul Tetapan Sistem sehingga Log Sistem. Walau bagaimanapun, penglibatan kerja hanya dilakukan selama dua hari kerana saya telah mengambil cuti kecemasan bagi baki tiga hari yang lain. Masa yang ada digunakan untuk memastikan draf dokumentasi modul akhir disiapkan sebelum cuti bermula. Saya mendapat pendedahan mengenai pengurusan masa dan tanggungjawab kerja apabila perlu menyiapkan tugasan penting sebelum mengambil cuti. Selain itu, saya mempelajari fungsi teknikal di bawah modul Meja Bantuan seperti pengurusan status kerja. Latihan minggu ini memberi impak terhadap kepentingan komunikasi yang jelas bersama penyelia ketika memohon cuti kecemasan bagi memastikan kelancaran operasi pejabat. Saya juga memahami aliran sokongan teknikal sistem dan merasa lebih bertanggungjawab dalam menguruskan tugasan dokumentasi yang diberikan walaupun dalam kekangan waktu yang singkat.', 'reflection_en' => 'Week two activities focused on continuing the remaining User Manual for the System Settings module up to System Log. However, work involvement was only for two days as I took emergency leave for the remaining three days. The available time was used to ensure the final module documentation draft was completed before the leave began. I gained exposure on time management and work responsibility when needing to complete important tasks before taking leave. Additionally, I learned technical functions under the Helpdesk module such as work status management. This week\'s training highlighted the importance of clear communication with supervisors when applying for emergency leave to ensure smooth office operations. I also understood the system technical support workflow and felt more responsible in managing documentation tasks given despite the short time constraint.'],
            ['title_ms' => 'MINGGU 3', 'title_en' => 'WEEK 3', 'start_date' => '2026-01-26', 'end_date' => '2026-01-30', 'days' => [
                ['day_ms' => 'Isnin', 'day_en' => 'Monday', 'activities_ms' => ['Penyerahan Draf Manual Pengguna Sistem mySafe.', 'Menghantar draf lengkap Manual Pengguna sistem mySafe kepada penyelia untuk semakan kualiti.', 'Menerima maklum balas daripada penyelia untuk memasukkan gambar rajah bagi setiap modul.', 'Menjalankan proses tangkapan skrin (screenshot) bagi fungsi utama dalam sistem mySafe.', 'Mula memasukkan gambar rajah ke dalam dokumen manual bagi menyokong penerangan teks.', 'Memastikan kedudukan gambar selari dengan urutan langkah kerja yang ditulis.'], 'activities_en' => ['Submission of mySafe System User Manual Draft.', 'Submitted complete User Manual draft for mySafe system to supervisor for quality review.', 'Received feedback from supervisor to include diagrams for each module.', 'Performed screenshot process for main functions in the mySafe system.', 'Started inserting diagrams into the manual document to support text descriptions.', 'Ensured image placement aligned with the written workflow sequence.']],
                ['day_ms' => 'Selasa', 'day_en' => 'Tuesday', 'activities_ms' => ['Penyambungan Kemaskini Visual Manual Pengguna Sistem mySafe.', 'Menyambung proses mengambil tangkapan skrin bagi Modul Pentadbiran.', 'Menyusun gambar rajah mengikut turutan fungsi.', 'Memberi label pada setiap tangkapan skrin.', 'Melaraskan saiz dan kedudukan visual supaya dokumen manual nampak lebih kemas dan teratur.'], 'activities_en' => ['Continued Visual Update of mySafe System User Manual.', 'Continued screenshot process for Administration Module.', 'Organised diagrams following function sequence.', 'Labelled each screenshot.', 'Adjusted size and visual positioning to make manual document neater and more organised.']],
                ['day_ms' => 'Rabu', 'day_en' => 'Wednesday', 'activities_ms' => ['Pemasangan Persekitaran Pembangunan (Laragon) dan Pengurusan Pangkalan Data (SqlYog) untuk Sistem LKIM.', 'Memasang dan mengkonfigurasi Laragon sebagai pelayan tempatan (local server) untuk menjalankan aplikasi web.', 'Membuka perisian SqlYog.', 'Mencipta pangkalan data baharu dan mengimport fail .sql sistem LKIM ke dalam sql melalui SqlYog.', 'Mengubahsuai fail konfigurasi sistem untuk menghubungkan kod sumber (source code) dengan pangkalan data yang telah diimport.', 'Menjalankan (run) sistem LKIM pada pelayan web melalui Laragon bagi memastikan sistem berfungsi sepenuhnya secara offline.'], 'activities_en' => ['Installation of Development Environment (Laragon) and Database Management (SqlYog) for LKIM System.', 'Installed and configured Laragon as local server to run web applications.', 'Opened SqlYog software.', 'Created new database and imported LKIM system .sql file into sql via SqlYog.', 'Modified system configuration files to connect source code with the imported database.', 'Ran LKIM system on web server via Laragon to ensure system functions fully offline.']],
                ['day_ms' => 'Khamis', 'day_en' => 'Thursday', 'activities_ms' => ['Pengujian Sistem LKIM.', 'Melakukan ujian fungsian pada setiap modul dalam sistem LKIM melalui pelayan tempatan.', 'Melakukan simulasi input data pada borang sistem untuk mengesan sebarang bugs atau kegagalan fungsi.', 'Merekodkan setiap penemuan ralat ke dalam Google Sheets secara sistematik untuk semakan pengelid.'], 'activities_en' => ['LKIM System Testing.', 'Performed functional testing on each module in the LKIM system via local server.', 'Simulated data input on system forms to detect any bugs or function failures.', 'Recorded each error finding into Google Sheets systematically for reviewer verification.']],
                ['day_ms' => 'Jumaat', 'day_en' => 'Friday', 'activities_ms' => ['Mesyuarat Penyelarasan Projek Swcorp.', 'Menghadiri mesyuarat secara bersemuka bersama Encik Syafiq dan Acap.', 'Mendengar penjelasan mengenai keperluan semasa pihak pelanggan terhadap sistem.', 'Mencatat setiap butiran spesifikasi teknikal dan aliran kerja yang dimahukan oleh pihak client.', 'Melakukan sesi soal jawab ringkas.'], 'activities_en' => ['Swcorp Project Coordination Meeting.', 'Attended face-to-face meeting with Encik Syafiq and Acap.', 'Listened to explanation on current customer requirements for the system.', 'Noted every technical specification detail and workflow desired by the client.', 'Conducted brief Q&A session.']],
            ], 'reflection_ms' => 'Aktiviti minggu ini dimulakan dengan mengemas kini manual mySafe melalui penambahan gambar rajah mengikut arahan penyelia. Seterusnya, saya mempelajari penggunaan perisian Laragon dan SqlYog untuk menjalankan serta menguruskan pangkalan data sistem LKIM. Saya berjaya menguasai kemahiran mengediakan persekitaran pelayan tempatan menggunakan Laragon dan mengurus pangkalan data melalui SqlYog. Saya juga memperoleh kemahiran dalam pengujian kualiti perisian dan dokumentasi ralat menggunakan Google Sheets. Selain itu, saya turut menghadiri mesyuarat penyelarasan projek Swcorp bersama Encik Syafiq bagi memahami keperluan teknikal pihak pelanggan. Latihan pada minggu ini telah meningkatkan tahap ketelitian dan tahap analisis saya dalam memahami logik sesebuah sistem yang kompleks. Saya merasa lebih yakin untuk menggunakan alatan pembangunan yang profesional dan memahami kepentingan dokumentasi ralat. Secara keseluruhan, aktiviti ini telah memupuk sifat berdisiplin dan etika kerja yang baik dalam melaksanakan tugasan yang diberikan.', 'reflection_en' => 'This week\'s activities started with updating the mySafe manual by adding diagrams following supervisor\'s instructions. Subsequently, I learned to use Laragon and SqlYog software to run and manage the LKIM system database. I successfully mastered the skills of setting up a local server environment using Laragon and managing databases through SqlYog. I also acquired skills in software quality testing and error documentation using Google Sheets. Additionally, I attended a Swcorp project coordination meeting with Encik Syafiq to understand the client\'s technical requirements. Training this week has improved my level of thoroughness and analysis in understanding the logic of a complex system. I feel more confident using professional development tools and understanding the importance of error documentation. Overall, these activities have cultivated discipline and good work ethics in carrying out assigned tasks.'],
            ['title_ms' => 'MINGGU 4', 'title_en' => 'WEEK 4', 'start_date' => '2026-02-02', 'end_date' => '2026-02-06', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 5', 'title_en' => 'WEEK 5', 'start_date' => '2026-02-09', 'end_date' => '2026-02-13', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 6', 'title_en' => 'WEEK 6', 'start_date' => '2026-02-16', 'end_date' => '2026-02-20', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 7', 'title_en' => 'WEEK 7', 'start_date' => '2026-02-23', 'end_date' => '2026-02-27', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 8', 'title_en' => 'WEEK 8', 'start_date' => '2026-03-02', 'end_date' => '2026-03-06', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 9', 'title_en' => 'WEEK 9', 'start_date' => '2026-03-09', 'end_date' => '2026-03-13', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 10', 'title_en' => 'WEEK 10', 'start_date' => '2026-03-16', 'end_date' => '2026-03-20', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 11', 'title_en' => 'WEEK 11', 'start_date' => '2026-03-23', 'end_date' => '2026-03-27', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 12', 'title_en' => 'WEEK 12', 'start_date' => '2026-03-30', 'end_date' => '2026-04-03', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 13', 'title_en' => 'WEEK 13', 'start_date' => '2026-04-06', 'end_date' => '2026-04-10', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 14', 'title_en' => 'WEEK 14', 'start_date' => '2026-04-13', 'end_date' => '2026-04-17', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 15', 'title_en' => 'WEEK 15', 'start_date' => '2026-04-20', 'end_date' => '2026-04-24', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 16', 'title_en' => 'WEEK 16', 'start_date' => '2026-04-27', 'end_date' => '2026-05-01', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 17', 'title_en' => 'WEEK 17', 'start_date' => '2026-05-04', 'end_date' => '2026-05-08', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 18', 'title_en' => 'WEEK 18', 'start_date' => '2026-05-11', 'end_date' => '2026-05-15', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 19', 'title_en' => 'WEEK 19', 'start_date' => '2026-05-18', 'end_date' => '2026-05-22', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
            ['title_ms' => 'MINGGU 20', 'title_en' => 'WEEK 20', 'start_date' => '2026-05-25', 'end_date' => '2026-05-29', 'url' => '', 'days' => [], 'reflection_ms' => '', 'reflection_en' => ''],
        ];

        $this->seedBlockPage('ringkasan-aktiviti', [
            ['type' => 'hero', 'id' => 'ra_hero', 'data' => [
                'title_ms' => 'RINGKASAN AKTIVITI',
                'title_en' => 'ACTIVITY SUMMARY',
            ]],
            ['type' => 'text', 'id' => 'ra_intro', 'data' => [
                'icon'       => '📋',
                'heading_ms' => 'PENGENALAN JURNAL REFLEKSI',
                'heading_en' => 'REFLECTION JOURNAL INTRODUCTION',
                'text_ms'    => "Penulisan Jurnal Refleksi Latihan Industri adalah salah satu elemen penting dalam penilaian Kursus Latihan Industri. Pelajar dikehendaki mencatat segala aktiviti harian yang dilaksanakan di organisasi latihan. Setiap minggu pelajar perlu menulis refleksi dan mendapatkan pengesahan serta maklum balas daripada Penyelia. Jurnal Refleksi Latihan Industri pelajar ini akan dinilai oleh Pengurus Industri.\n\nDi samping itu, sepanjang menjalani latihan industri ini, saya didedahkan dengan perkara-perkara dan pengalaman yang baru. Selain dari mempraktikkan apa yang telah saya belajar sepanjang lima (5) semester pengajian di Politeknik Sultan Idris Shah, saya juga telah didedahkan bagaimana cara untuk mengikuti setiap arahan dan peraturan-peraturan yang telah ditetapkan sepanjang saya menjalani latihan industri di Opensoft Technologies. Di syarikat ini, saya telah diletakkan di Bahagian Pembangunan Perisian. Tempoh perkhidmatan saya bermula pada hari Isnin sehingga hari Jumaat mengikut waktu bekerja yang ditetapkan iaitu dari jam 8.30 pagi sehingga 5.30 petang. Berikut merupakan ringkasan mingguan sepanjang saya menjalani latihan industri selama 20 minggu (12 Januari 2026 sehingga 29 Mei 2026).",
                'text_en'    => "Writing the Industrial Training Reflection Journal is one of the important elements in the assessment of the Industrial Training Course. Students are required to record all daily activities carried out at the training organisation. Each week, students need to write reflections and obtain verification and feedback from their Supervisor. The student's Industrial Training Reflection Journal will be assessed by the Industry Manager.\n\nIn addition, throughout this industrial training, I was exposed to new things and experiences. Apart from practising what I learned during five (5) semesters of studies at Politeknik Sultan Idris Shah, I was also exposed to how to follow every instruction and regulation set throughout my industrial training at Opensoft Technologies. At this company, I was placed in the Software Development Department. My service period is from Monday to Friday following the working hours set from 8.30 am to 5.30 pm. The following is a weekly summary throughout my 20-week industrial training (12 January 2026 to 29 May 2026).",
            ]],
            ['type' => 'weekly-grid', 'id' => 'ra_weeks', 'data' => [
                'heading_ms' => 'MINGGU 1 - 20',
                'heading_en' => 'WEEK 1 - 20',
                'items'      => $weeks,
            ]],
        ]);
    }
}
